export const wyrPrompts = [
  "Would you rather fight one horse-sized duck or one hundred duck-sized horses?",
  "Would you rather always have to sing your thoughts or dance everywhere you go?",
  "Would you rather be able to teleport anywhere once a day or pause time for ten seconds once a day?",
  "Would you rather only speak in rhymes or only speak in movie quotes?",
  "Would you rather explore the deep ocean or outer space?",
  "Would you rather have unlimited snacks or unlimited games?",
  "Would you rather never need sleep again or never need to wait in line again?",
  "Would you rather survive a zombie apocalypse with only a frying pan or only a bicycle?",
  "Would you rather be permanently stuck at 1 HP or have every boss battle start with dramatic anime music?",
  "Would you rather always lag in online games or always have stick drift at the worst possible moment?",
  "Would you rather have a perfect gaming setup with bad Wi-Fi or amazing Wi-Fi with a cursed chair?",
  "Would you rather be the funniest person in every voice chat or the smartest person in every raid?",
  "Would you rather have to narrate everything you do like a sports commentator or whisper everything dramatically like a movie trailer?",
  "Would you rather find a legendary sword in real life or a working portal gun with one battery left?",
  "Would you rather live in a world with dragons or a world with giant mechs?",
  "Would you rather always know the best meme at the perfect time or always know the exact answer to trivia night?",
  "Would you rather be trapped in your favorite game for one week or your favorite movie for one week?",
  "Would you rather have a pet mimic that steals your socks or a pet slime that keeps eating your snacks?",
  "Would you rather win every coin flip or always roll a natural 20 once a day?",
  "Would you rather survive on a deserted island with your best friend or with your most competent group chat member?",
  "Would you rather have unlimited energy drinks with no crash or unlimited pizza with no consequences?",
  "Would you rather be able to quick-save in real life or mute one annoying sound per day?",
  "Would you rather every door make a boss-battle sound effect or every chair you sit in squeak dramatically?",
  "Would you rather discover aliens are chill gamers or that dolphins have been judging us this whole time?",
  "Would you rather only be able to communicate with GIF reactions or with soundboard effects?",
  "Would you rather always spawn with perfect loot but no map or a perfect map but terrible loot?",
  "Would you rather have to solve one escape room every Monday or one raid mechanic every Friday?",
  "Would you rather own a spaceship with terrible cup holders or a castle with awful Wi-Fi?",
  "Would you rather be famous for one incredible speedrun or one insanely lucky clutch play?",
  "Would you rather have a real-life inventory screen or a real-life quest log?",
  "Would you rather be able to summon one helpful NPC a day or reroll one bad decision a week?",
];
